### ISSUE TITLE
header links

### ISSUE THREAD

**Issue by rubillionaire** [risd/edu-style-guide#5]
`header` styles should account for any `h1` being wrapped in an `a` tag. Currently, they do not, and the `h1` is getting underlined.

![screen shot 2015-06-22 at 9 55 11 am](https://cloud.githubusercontent.com/assets/434737/8283336/c990d70a-18c4-11e5-9ed7-34aacd4631eb.png)

**Comment by micahmicah** [comment]
c1e358773e6b07a40ebd9aeccc4720688f7246a9
